export const Products = [
    { id: 1, name: 'Panadol', isAddedToCart: false, quantity: 1, price: '18.00', imageName: require('../../assets/panadol.png'), description: 'As one of the worlds leading paracetamol-based pain relievers, Panadols clinically-proven products can treat your pain and get you feeling yourself again.' },
    { id: 2, name: 'Arinac Forte', isAddedToCart: false, quantity: 0, price: '50.00', imageName: require('../../assets/arinac.png'), description: 'Arinac Forte Tablet is composed of ibuprofen and pseudoephedrine. The tablet acts as a non-steroidal anti-inflammatory drug (NSAID) that controls hormones in the body which cause pain and inflammation. Also works as a decongestant and shrinks the dilated blood vessels to clear nasal congestion' },
    { id: 3, name: 'Risek 40 Tablet', isAddedToCart: false, quantity: 0, price: '120.00', imageName: require('../../assets/risek.png'), description: 'Risek contains omeprazole which belongs to the class of proton-pump inhibitors. This class of drugs is the most potent inhibitor of acid secretion from the stomach. Its mechanism of action involves the inhibition of the H/K ATP-ase pump which blocks the production of acid in the stomach.' },
    { id: 4, name: 'Amoxil 125mg Syrup', isAddedToCart: false, quantity: 0, price: '128.00', imageName: require('../../assets/amoxil.png'), description: 'Amoxycillin 125mg Syrup is an antibiotic medicine with versatile actions. It can treat a multitude of bacterial infections including those of the ears, eyes, nose, sinus, tonsils, tooth, throat, lungs, skin, gastrointestinal tract, and urinary tract. It may also be effective against peptic ulcer disease.' },
    { id: 5, name: 'Telfast 120mg', isAddedToCart: false, quantity: 2, price: '75.00', imageName: require('../../assets/telfast.png'), description: 'Fast, non drowsy 24 hr relief of the symptoms of seasonal hayfever allergies.' },
    { id: 6, name: 'Coferb Cough Syrup', isAddedToCart: false, quantity: 4, price: '90.00', imageName: require('../../assets/coferb.png'), description: 'Coferb contains Ivy Leaf extract that relieves cough and congestion. It relieves cough naturally and makes breathing easy. Formulations similar to Coferb have been recognized by international clinical trials endorsing safety and efficacy of the product. Ivy Leaf extract based syrups are widely accepted and used in Europe and USA.' },
    { id: 7, name: 'ColdAct', isAddedToCart: false, quantity: 0, price: '28.00', imageName: require('../../assets/coldact.png'), description: 'Coldact Capsule is a medicine used in the treatment of common cold symptoms. It provides relief from symptoms such as headache, sore throat, runny nose, muscular pain, and fever.' },
    { id: 8, name: 'Fepanil 250mg', isAddedToCart: false, quantity: 0, price: '68.00', imageName: require('../../assets/fepanil.png'), description: 'FEPANIL 250 MG SUSPENSION is a widely prescribed medicine that helps to ease pain and bring down high body temperature (fever). In children, it treats conditions like headache, toothache, body ache, fever, and common cold.' },
    { id: 9, name: 'CEFOLAC', isAddedToCart: false, quantity: 0, price: '98.00', imageName: require('../../assets/cefolac.jpeg'), description: 'Cefolac 200 Tablet is an antibiotic belonging that is used to treat a variety of bacterial infections. It is effective in infections of the respiratory tract (eg. pneumonia), urinary tract, ear, nasal sinus, throat, and some sexually transmitted diseases.' },
    { id: 10, name: 'DIZIPEN', isAddedToCart: false, quantity: 0, price: '118.00', imageName: require('../../assets/digipen.jpeg'), description: 'Digipen Syrup is used as appetite stimulants and helps in digestive disturbance & impaired production of gastric juice. It is used for gastrointestinal purposes as digestive aid, for the treatment of indigestion, flatulence, hyperacidity, bloating, stomach cramps and various other types of digestion related problems.' },
    { id: 11, name: 'Ascoril LS', isAddedToCart: false, quantity: 0, price: '118.00', imageName: require('../../assets/acrosills.jpeg'), description: 'Ascoril LS Syrup is a combination medicine used in the treatment of cough with mucus. It thins mucus in the nose, windpipe, and lungs, making it easier to cough out. It also provides relief from runny nose, sneezing, itching, and watery eyes.' },
    { id: 12, name: 'Ascoril Flu', isAddedToCart: false, quantity: 0, price: '158.00', imageName: require('../../assets/acrosilflu.jpeg'), description: 'Ascoril Flu Syrup is a combination medicine used in the treatment of common cold symptoms. It relieves allergy symptoms such as runny nose, stuffy nose, sneezing, watery eyes and congestion or stuffiness.' },
];
    